# This is a YAML configuration file to build and push a Docker image

trigger:
  branches:
    exclude:
      - '*'

pr jobs:
  - job: BuildAndPushDockerImage
    displayName: 'Build and Push Docker Image'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - checkout: self

      - task: Docker@2
        displayName: 'Build and Push'
        inputs:
          containerRegistry: 'Docker-Hub-Connection'
          repository: 'shivakrishna99'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          buildContext: '.'
          tags: 'latest'
