trigger:
  branches:
    exclude:
      - '*'

jobs:
  - job: BuildAndPushDockerImage
    displayName: 'Build and Push Docker Image'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - checkout: self

      - task: Docker@2
        displayName: 'Build Docker image'
        inputs:
          command: 'build'
          containerRegistry: 'Docker-Hub-Connection'
          repository: 'shivakrishna99/odoo'
          dockerfile: '**/Dockerfile'
          buildContext: '$(Build.SourcesDirectory)'
          tags: |
            latest
            $(Build.BuildId)

      - task: Docker@2
        displayName: 'Push Docker image'
        inputs:
          command: 'push'
          containerRegistry: 'Docker-Hub-Connection'
          repository: 'shivakrishna99/odoo'
          tags: |
            latest
            $(Build.BuildId)
